//! Icon geometry taken from Tabler Icons.
//!
//! Generated by `tools/icon-import`. Do not edit: run
//! `scripts/import-icons.sh` instead, and change `tools/icon-import/icons.txt`
//! to change which icon stands behind which glyph.
//!
//! Tabler Icons is Copyright (c) 2020-2024 Paweł Kuna and is offered under the
//! MIT licence, whose terms are reproduced in `licenses/LICENSE-Tabler.txt`.
//! The MIT licence imposes no copyleft, so this geometry travels inside an
//! AGPL binary without changing anything about it, as long as the notice
//! travels with it.
//!
//! Coordinates are the source artwork's 24 unit box scaled to the 1000 unit
//! box `super::UNITS` defines, so 1 source pixel is 41 and two thirds units.
//! Curves are cubics because that is what the source uses; quadratics and
//! elliptical arcs were resolved into cubics at import time, in `f64`, before
//! anything was rounded.

use super::Cmd;
use crate::Glyph;

/// Every outline of one glyph.
///
/// Deliberately total rather than fallible. A glyph with no artwork would draw
/// nothing at all, and nothing at all is invisible rather than wrong, so the
/// compiler is made to refuse a `Glyph` variant that `icons.txt` does not
/// name.
pub(super) fn outline(glyph: Glyph) -> &'static [&'static [Cmd]] {
    match glyph {
        Glyph::App => APP,
        Glyph::Book => BOOK,
        Glyph::Note => NOTE,
        Glyph::Clock => CLOCK,
        Glyph::Settings => SETTINGS,
        Glyph::Folder => FOLDER,
        Glyph::Chart => CHART,
        Glyph::Search => SEARCH,
        Glyph::Reader => READER,
        Glyph::Power => POWER,
        Glyph::Grid => GRID,
        Glyph::Circle => CIRCLE,
        Glyph::Check => CHECK,
        Glyph::Terminal => TERMINAL,
        Glyph::Chat => CHAT,
        Glyph::News => NEWS,
        Glyph::Rss => RSS,
        Glyph::Light => LIGHT,
        Glyph::Close => CLOSE,
        Glyph::Download => DOWNLOAD,
        Glyph::Bookmark => BOOKMARK,
        Glyph::Heart => HEART,
        Glyph::Filter => FILTER,
        Glyph::Person => PERSON,
        Glyph::Tag => TAG,
        Glyph::Globe => GLOBE,
        Glyph::Refresh => REFRESH,
        Glyph::More => MORE,
        Glyph::Bluetooth => BLUETOOTH,
        Glyph::Key => KEY,
        Glyph::Magnet => MAGNET,
        Glyph::Play => PLAY,
        Glyph::Pause => PAUSE,
        Glyph::Rewind30 => REWIND30,
        Glyph::Forward30 => FORWARD30,
        Glyph::VolumeDown => VOLUME_DOWN,
        Glyph::VolumeUp => VOLUME_UP,
        Glyph::MoreVertical => MORE_VERTICAL,
        Glyph::Previous => PREVIOUS,
        Glyph::Next => NEXT,
        Glyph::Trash => TRASH,
        Glyph::Wifi => WIFI,
        Glyph::Battery => BATTERY,
        Glyph::Plus => PLUS,
        Glyph::Headphones => HEADPHONES,
        Glyph::Minus => MINUS,
        Glyph::SwapVertical => SWAP_VERTICAL,
        Glyph::ChessWhiteKing => CHESS_WHITE_KING,
        Glyph::ChessWhiteQueen => CHESS_WHITE_QUEEN,
        Glyph::ChessWhiteRook => CHESS_WHITE_ROOK,
        Glyph::ChessWhiteBishop => CHESS_WHITE_BISHOP,
        Glyph::ChessWhiteKnight => CHESS_WHITE_KNIGHT,
        Glyph::ChessWhitePawn => CHESS_WHITE_PAWN,
        Glyph::ChessBlackKing => CHESS_BLACK_KING,
        Glyph::ChessBlackQueen => CHESS_BLACK_QUEEN,
        Glyph::ChessBlackRook => CHESS_BLACK_ROOK,
        Glyph::ChessBlackBishop => CHESS_BLACK_BISHOP,
        Glyph::ChessBlackKnight => CHESS_BLACK_KNIGHT,
        Glyph::ChessBlackPawn => CHESS_BLACK_PAWN,
        // Board pieces are discs and rings rather than line art, so they are
        // filled in `game_piece_shapes` instead of stroked from an outline.
        Glyph::BlackDisc
        | Glyph::WhiteDisc
        | Glyph::BlackDraughtsKing
        | Glyph::WhiteDraughtsKing
        | Glyph::BlackDraughtsMan
        | Glyph::WhiteDraughtsMan
        | Glyph::BoardPoint
        | Glyph::Mill
        | Glyph::LegalPoint
        | Glyph::Backspace
        | Glyph::Shift => &[],
    }
}

/// `apps` from Tabler Icons.
static APP: &[&[Cmd]] = &[
    &[
        Cmd::Move(167, 208),
        Cmd::Cubic(167, 185, 185, 167, 208, 167),
        Cmd::Line(375, 167),
        Cmd::Cubic(398, 167, 417, 185, 417, 208),
        Cmd::Line(417, 375),
        Cmd::Cubic(417, 398, 398, 417, 375, 417),
        Cmd::Line(208, 417),
        Cmd::Cubic(185, 417, 167, 398, 167, 375),
        Cmd::Line(167, 208),
    ],
    &[
        Cmd::Move(167, 625),
        Cmd::Cubic(167, 602, 185, 583, 208, 583),
        Cmd::Line(375, 583),
        Cmd::Cubic(398, 583, 417, 602, 417, 625),
        Cmd::Line(417, 792),
        Cmd::Cubic(417, 815, 398, 833, 375, 833),
        Cmd::Line(208, 833),
        Cmd::Cubic(185, 833, 167, 815, 167, 792),
        Cmd::Line(167, 625),
    ],
    &[
        Cmd::Move(583, 625),
        Cmd::Cubic(583, 602, 602, 583, 625, 583),
        Cmd::Line(792, 583),
        Cmd::Cubic(815, 583, 833, 602, 833, 625),
        Cmd::Line(833, 792),
        Cmd::Cubic(833, 815, 815, 833, 792, 833),
        Cmd::Line(625, 833),
        Cmd::Cubic(602, 833, 583, 815, 583, 792),
        Cmd::Line(583, 625),
    ],
    &[Cmd::Move(583, 292), Cmd::Line(833, 292)],
    &[Cmd::Move(708, 167), Cmd::Line(708, 417)],
];

/// `book` from Tabler Icons.
static BOOK: &[&[Cmd]] = &[
    &[
        Cmd::Move(125, 792),
        Cmd::Cubic(241, 725, 384, 725, 500, 792),
        Cmd::Cubic(616, 725, 759, 725, 875, 792),
    ],
    &[
        Cmd::Move(125, 250),
        Cmd::Cubic(241, 183, 384, 183, 500, 250),
        Cmd::Cubic(616, 183, 759, 183, 875, 250),
    ],
    &[Cmd::Move(125, 250), Cmd::Line(125, 792)],
    &[Cmd::Move(500, 250), Cmd::Line(500, 792)],
    &[Cmd::Move(875, 250), Cmd::Line(875, 792)],
];

/// `note` from Tabler Icons.
static NOTE: &[&[Cmd]] = &[
    &[Cmd::Move(542, 833), Cmd::Line(833, 542)],
    &[
        Cmd::Move(542, 833),
        Cmd::Line(542, 583),
        Cmd::Cubic(542, 560, 560, 542, 583, 542),
        Cmd::Line(833, 542),
        Cmd::Line(833, 250),
        Cmd::Cubic(833, 204, 796, 167, 750, 167),
        Cmd::Line(250, 167),
        Cmd::Cubic(204, 167, 167, 204, 167, 250),
        Cmd::Line(167, 750),
        Cmd::Cubic(167, 796, 204, 833, 250, 833),
        Cmd::Line(542, 833),
    ],
];

/// `clock` from Tabler Icons.
static CLOCK: &[&[Cmd]] = &[
    &[
        Cmd::Move(125, 500),
        Cmd::Cubic(125, 707, 293, 875, 500, 875),
        Cmd::Cubic(707, 875, 875, 707, 875, 500),
        Cmd::Cubic(875, 293, 707, 125, 500, 125),
        Cmd::Cubic(293, 125, 125, 293, 125, 500),
    ],
    &[
        Cmd::Move(500, 292),
        Cmd::Line(500, 500),
        Cmd::Line(625, 625),
    ],
];

/// `settings` from Tabler Icons.
static SETTINGS: &[&[Cmd]] = &[
    &[
        Cmd::Move(430, 180),
        Cmd::Cubic(448, 107, 552, 107, 570, 180),
        Cmd::Cubic(575, 202, 591, 221, 612, 229),
        Cmd::Cubic(633, 238, 657, 236, 677, 224),
        Cmd::Cubic(741, 185, 815, 259, 776, 323),
        Cmd::Cubic(764, 343, 762, 367, 771, 388),
        Cmd::Cubic(780, 409, 798, 425, 820, 430),
        Cmd::Cubic(893, 448, 893, 552, 820, 570),
        Cmd::Cubic(798, 575, 779, 591, 771, 612),
        Cmd::Cubic(762, 633, 764, 657, 776, 677),
        Cmd::Cubic(815, 741, 741, 815, 677, 776),
        Cmd::Cubic(657, 764, 633, 762, 612, 771),
        Cmd::Cubic(591, 780, 575, 798, 570, 820),
        Cmd::Cubic(552, 893, 448, 893, 430, 820),
        Cmd::Cubic(425, 798, 409, 779, 388, 771),
        Cmd::Cubic(367, 762, 343, 764, 323, 776),
        Cmd::Cubic(259, 815, 185, 741, 224, 677),
        Cmd::Cubic(236, 657, 238, 633, 229, 612),
        Cmd::Cubic(220, 591, 202, 575, 180, 570),
        Cmd::Cubic(107, 552, 107, 448, 180, 430),
        Cmd::Cubic(202, 425, 221, 409, 229, 388),
        Cmd::Cubic(238, 367, 236, 343, 224, 323),
        Cmd::Cubic(185, 259, 259, 185, 323, 224),
        Cmd::Cubic(365, 250, 419, 227, 430, 180),
    ],
    &[
        Cmd::Move(375, 500),
        Cmd::Cubic(375, 569, 431, 625, 500, 625),
        Cmd::Cubic(569, 625, 625, 569, 625, 500),
        Cmd::Cubic(625, 431, 569, 375, 500, 375),
        Cmd::Cubic(431, 375, 375, 431, 375, 500),
    ],
];

/// `folder` from Tabler Icons.
static FOLDER: &[&[Cmd]] = &[&[
    Cmd::Move(208, 167),
    Cmd::Line(375, 167),
    Cmd::Line(500, 292),
    Cmd::Line(792, 292),
    Cmd::Cubic(838, 292, 875, 329, 875, 375),
    Cmd::Line(875, 708),
    Cmd::Cubic(875, 754, 838, 792, 792, 792),
    Cmd::Line(208, 792),
    Cmd::Cubic(162, 792, 125, 754, 125, 708),
    Cmd::Line(125, 250),
    Cmd::Cubic(125, 204, 162, 167, 208, 167),
]];

/// `chart-bar` from Tabler Icons.
static CHART: &[&[Cmd]] = &[
    &[
        Cmd::Move(125, 542),
        Cmd::Cubic(125, 519, 144, 500, 167, 500),
        Cmd::Line(333, 500),
        Cmd::Cubic(356, 500, 375, 519, 375, 542),
        Cmd::Line(375, 792),
        Cmd::Cubic(375, 815, 356, 833, 333, 833),
        Cmd::Line(167, 833),
        Cmd::Cubic(144, 833, 125, 815, 125, 792),
        Cmd::Line(125, 542),
    ],
    &[
        Cmd::Move(625, 375),
        Cmd::Cubic(625, 352, 644, 333, 667, 333),
        Cmd::Line(833, 333),
        Cmd::Cubic(856, 333, 875, 352, 875, 375),
        Cmd::Line(875, 792),
        Cmd::Cubic(875, 815, 856, 833, 833, 833),
        Cmd::Line(667, 833),
        Cmd::Cubic(644, 833, 625, 815, 625, 792),
        Cmd::Line(625, 375),
    ],
    &[
        Cmd::Move(375, 208),
        Cmd::Cubic(375, 185, 394, 167, 417, 167),
        Cmd::Line(583, 167),
        Cmd::Cubic(606, 167, 625, 185, 625, 208),
        Cmd::Line(625, 792),
        Cmd::Cubic(625, 815, 606, 833, 583, 833),
        Cmd::Line(417, 833),
        Cmd::Cubic(394, 833, 375, 815, 375, 792),
        Cmd::Line(375, 208),
    ],
    &[Cmd::Move(167, 833), Cmd::Line(750, 833)],
];

/// `search` from Tabler Icons.
static SEARCH: &[&[Cmd]] = &[
    &[
        Cmd::Move(125, 417),
        Cmd::Cubic(125, 578, 256, 708, 417, 708),
        Cmd::Cubic(578, 708, 708, 578, 708, 417),
        Cmd::Cubic(708, 256, 578, 125, 417, 125),
        Cmd::Cubic(256, 125, 125, 256, 125, 417),
    ],
    &[Cmd::Move(875, 875), Cmd::Line(625, 625)],
];

/// `device-ipad` from Tabler Icons.
static READER: &[&[Cmd]] = &[
    &[
        Cmd::Move(750, 125),
        Cmd::Cubic(796, 125, 833, 162, 833, 208),
        Cmd::Line(833, 792),
        Cmd::Cubic(833, 838, 796, 875, 750, 875),
        Cmd::Line(250, 875),
        Cmd::Cubic(204, 875, 167, 838, 167, 792),
        Cmd::Line(167, 208),
        Cmd::Cubic(167, 162, 204, 125, 250, 125),
        Cmd::Line(750, 125),
    ],
    &[Cmd::Move(375, 750), Cmd::Line(625, 750)],
];

/// `power` from Tabler Icons.
static POWER: &[&[Cmd]] = &[
    &[
        Cmd::Move(292, 250),
        Cmd::Cubic(188, 337, 150, 480, 197, 608),
        Cmd::Cubic(243, 735, 364, 820, 500, 820),
        Cmd::Cubic(636, 820, 757, 735, 803, 608),
        Cmd::Cubic(850, 480, 812, 337, 708, 250),
    ],
    &[Cmd::Move(500, 167), Cmd::Line(500, 500)],
];

/// `layout-grid` from Tabler Icons.
static GRID: &[&[Cmd]] = &[
    &[
        Cmd::Move(167, 208),
        Cmd::Cubic(167, 185, 185, 167, 208, 167),
        Cmd::Line(375, 167),
        Cmd::Cubic(398, 167, 417, 185, 417, 208),
        Cmd::Line(417, 375),
        Cmd::Cubic(417, 398, 398, 417, 375, 417),
        Cmd::Line(208, 417),
        Cmd::Cubic(185, 417, 167, 398, 167, 375),
        Cmd::Line(167, 208),
    ],
    &[
        Cmd::Move(583, 208),
        Cmd::Cubic(583, 185, 602, 167, 625, 167),
        Cmd::Line(792, 167),
        Cmd::Cubic(815, 167, 833, 185, 833, 208),
        Cmd::Line(833, 375),
        Cmd::Cubic(833, 398, 815, 417, 792, 417),
        Cmd::Line(625, 417),
        Cmd::Cubic(602, 417, 583, 398, 583, 375),
        Cmd::Line(583, 208),
    ],
    &[
        Cmd::Move(167, 625),
        Cmd::Cubic(167, 602, 185, 583, 208, 583),
        Cmd::Line(375, 583),
        Cmd::Cubic(398, 583, 417, 602, 417, 625),
        Cmd::Line(417, 792),
        Cmd::Cubic(417, 815, 398, 833, 375, 833),
        Cmd::Line(208, 833),
        Cmd::Cubic(185, 833, 167, 815, 167, 792),
        Cmd::Line(167, 625),
    ],
    &[
        Cmd::Move(583, 625),
        Cmd::Cubic(583, 602, 602, 583, 625, 583),
        Cmd::Line(792, 583),
        Cmd::Cubic(815, 583, 833, 602, 833, 625),
        Cmd::Line(833, 792),
        Cmd::Cubic(833, 815, 815, 833, 792, 833),
        Cmd::Line(625, 833),
        Cmd::Cubic(602, 833, 583, 815, 583, 792),
        Cmd::Line(583, 625),
    ],
];

/// `circle` from Tabler Icons.
static CIRCLE: &[&[Cmd]] = &[&[
    Cmd::Move(125, 500),
    Cmd::Cubic(125, 707, 293, 875, 500, 875),
    Cmd::Cubic(707, 875, 875, 707, 875, 500),
    Cmd::Cubic(875, 293, 707, 125, 500, 125),
    Cmd::Cubic(293, 125, 125, 293, 125, 500),
]];

/// `check` from Tabler Icons.
static CHECK: &[&[Cmd]] = &[&[
    Cmd::Move(208, 500),
    Cmd::Line(417, 708),
    Cmd::Line(833, 292),
]];

/// `terminal-2` from Tabler Icons.
static TERMINAL: &[&[Cmd]] = &[
    &[
        Cmd::Move(333, 375),
        Cmd::Line(458, 500),
        Cmd::Line(333, 625),
    ],
    &[Cmd::Move(542, 625), Cmd::Line(667, 625)],
    &[
        Cmd::Move(125, 250),
        Cmd::Cubic(125, 204, 162, 167, 208, 167),
        Cmd::Line(792, 167),
        Cmd::Cubic(838, 167, 875, 204, 875, 250),
        Cmd::Line(875, 750),
        Cmd::Cubic(875, 796, 838, 833, 792, 833),
        Cmd::Line(208, 833),
        Cmd::Cubic(162, 833, 125, 796, 125, 750),
        Cmd::Line(125, 250),
    ],
];

/// `message-circle` from Tabler Icons.
static CHAT: &[&[Cmd]] = &[&[
    Cmd::Move(125, 833),
    Cmd::Line(179, 671),
    Cmd::Cubic(82, 528, 120, 343, 267, 239),
    Cmd::Cubic(414, 134, 625, 143, 760, 259),
    Cmd::Cubic(896, 374, 914, 561, 803, 696),
    Cmd::Cubic(692, 831, 486, 872, 321, 792),
    Cmd::Line(125, 833),
]];

/// `news` from Tabler Icons.
static NEWS: &[&[Cmd]] = &[
    &[
        Cmd::Move(667, 250),
        Cmd::Line(792, 250),
        Cmd::Cubic(815, 250, 833, 269, 833, 292),
        Cmd::Line(833, 750),
        Cmd::Cubic(833, 796, 796, 833, 750, 833),
        Cmd::Cubic(704, 833, 667, 796, 667, 750),
        Cmd::Line(667, 208),
        Cmd::Cubic(667, 185, 648, 167, 625, 167),
        Cmd::Line(208, 167),
        Cmd::Cubic(185, 167, 167, 185, 167, 208),
        Cmd::Line(167, 708),
        Cmd::Cubic(167, 777, 223, 833, 292, 833),
        Cmd::Line(750, 833),
    ],
    &[Cmd::Move(333, 333), Cmd::Line(500, 333)],
    &[Cmd::Move(333, 500), Cmd::Line(500, 500)],
    &[Cmd::Move(333, 667), Cmd::Line(500, 667)],
];

/// `rss` from Tabler Icons.
static RSS: &[&[Cmd]] = &[
    &[
        Cmd::Move(167, 792),
        Cmd::Cubic(167, 815, 185, 833, 208, 833),
        Cmd::Cubic(231, 833, 250, 815, 250, 792),
        Cmd::Cubic(250, 769, 231, 750, 208, 750),
        Cmd::Cubic(185, 750, 167, 769, 167, 792),
    ],
    &[
        Cmd::Move(167, 167),
        Cmd::Cubic(535, 167, 833, 465, 833, 833),
    ],
    &[
        Cmd::Move(167, 458),
        Cmd::Cubic(374, 458, 542, 626, 542, 833),
    ],
];

/// `bulb` from Tabler Icons.
static LIGHT: &[&[Cmd]] = &[
    &[
        Cmd::Move(125, 500),
        Cmd::Line(167, 500),
        Cmd::Move(500, 125),
        Cmd::Line(500, 167),
        Cmd::Move(833, 500),
        Cmd::Line(875, 500),
        Cmd::Move(233, 233),
        Cmd::Line(263, 263),
        Cmd::Move(767, 233),
        Cmd::Line(737, 263),
    ],
    &[
        Cmd::Move(375, 667),
        Cmd::Cubic(303, 613, 274, 519, 302, 434),
        Cmd::Cubic(331, 349, 410, 292, 500, 292),
        Cmd::Cubic(590, 292, 669, 349, 698, 434),
        Cmd::Cubic(726, 519, 697, 613, 625, 667),
        Cmd::Cubic(592, 699, 577, 746, 583, 792),
        Cmd::Cubic(583, 838, 546, 875, 500, 875),
        Cmd::Cubic(454, 875, 417, 838, 417, 792),
        Cmd::Cubic(423, 746, 408, 699, 375, 667),
    ],
    &[Cmd::Move(404, 708), Cmd::Line(596, 708)],
];

/// `x` from Tabler Icons.
static CLOSE: &[&[Cmd]] = &[
    &[Cmd::Move(750, 250), Cmd::Line(250, 750)],
    &[Cmd::Move(250, 250), Cmd::Line(750, 750)],
];

/// `download` from Tabler Icons.
static DOWNLOAD: &[&[Cmd]] = &[
    &[
        Cmd::Move(167, 708),
        Cmd::Line(167, 792),
        Cmd::Cubic(167, 838, 204, 875, 250, 875),
        Cmd::Line(750, 875),
        Cmd::Cubic(796, 875, 833, 838, 833, 792),
        Cmd::Line(833, 708),
    ],
    &[
        Cmd::Move(292, 458),
        Cmd::Line(500, 667),
        Cmd::Line(708, 458),
    ],
    &[Cmd::Move(500, 167), Cmd::Line(500, 667)],
];

/// `bookmark` from Tabler Icons.
static BOOKMARK: &[&[Cmd]] = &[&[
    Cmd::Move(750, 292),
    Cmd::Line(750, 875),
    Cmd::Line(500, 708),
    Cmd::Line(250, 875),
    Cmd::Line(250, 292),
    Cmd::Cubic(250, 200, 325, 125, 417, 125),
    Cmd::Line(583, 125),
    Cmd::Cubic(675, 125, 750, 200, 750, 292),
]];

/// `heart` from Tabler Icons.
static HEART: &[&[Cmd]] = &[&[
    Cmd::Move(813, 524),
    Cmd::Line(500, 833),
    Cmd::Line(188, 524),
    Cmd::Cubic(131, 469, 111, 388, 134, 313),
    Cmd::Cubic(157, 238, 220, 182, 298, 169),
    Cmd::Cubic(375, 156, 453, 187, 500, 250),
    Cmd::Cubic(547, 188, 625, 157, 702, 170),
    Cmd::Cubic(779, 183, 842, 239, 865, 313),
    Cmd::Cubic(889, 388, 868, 469, 813, 524),
]];

/// `filter` from Tabler Icons.
static FILTER: &[&[Cmd]] = &[&[
    Cmd::Move(167, 167),
    Cmd::Line(833, 167),
    Cmd::Line(833, 257),
    Cmd::Cubic(833, 279, 825, 300, 809, 316),
    Cmd::Line(625, 500),
    Cmd::Line(625, 792),
    Cmd::Line(375, 875),
    Cmd::Line(375, 521),
    Cmd::Line(188, 316),
    Cmd::Cubic(174, 300, 167, 280, 167, 259),
    Cmd::Line(167, 167),
]];

/// `user` from Tabler Icons.
static PERSON: &[&[Cmd]] = &[
    &[
        Cmd::Move(333, 292),
        Cmd::Cubic(333, 384, 408, 458, 500, 458),
        Cmd::Cubic(592, 458, 667, 384, 667, 292),
        Cmd::Cubic(667, 200, 592, 125, 500, 125),
        Cmd::Cubic(408, 125, 333, 200, 333, 292),
    ],
    &[
        Cmd::Move(250, 875),
        Cmd::Line(250, 792),
        Cmd::Cubic(250, 700, 325, 625, 417, 625),
        Cmd::Line(583, 625),
        Cmd::Cubic(675, 625, 750, 700, 750, 792),
        Cmd::Line(750, 875),
    ],
];

/// `tag` from Tabler Icons.
static TAG: &[&[Cmd]] = &[
    &[
        Cmd::Move(271, 313),
        Cmd::Cubic(271, 336, 289, 354, 313, 354),
        Cmd::Cubic(336, 354, 354, 336, 354, 313),
        Cmd::Cubic(354, 289, 336, 271, 313, 271),
        Cmd::Cubic(289, 271, 271, 289, 271, 313),
    ],
    &[
        Cmd::Move(125, 250),
        Cmd::Line(125, 466),
        Cmd::Cubic(125, 488, 134, 509, 149, 524),
        Cmd::Line(471, 846),
        Cmd::Cubic(510, 885, 573, 885, 613, 846),
        Cmd::Line(846, 613),
        Cmd::Cubic(885, 573, 885, 510, 846, 471),
        Cmd::Line(524, 149),
        Cmd::Cubic(509, 134, 488, 125, 465, 125),
        Cmd::Line(250, 125),
        Cmd::Cubic(217, 125, 185, 138, 162, 162),
        Cmd::Cubic(138, 185, 125, 217, 125, 250),
    ],
];

/// `world` from Tabler Icons.
static GLOBE: &[&[Cmd]] = &[
    &[
        Cmd::Move(125, 500),
        Cmd::Cubic(125, 707, 293, 875, 500, 875),
        Cmd::Cubic(707, 875, 875, 707, 875, 500),
        Cmd::Cubic(875, 293, 707, 125, 500, 125),
        Cmd::Cubic(293, 125, 125, 293, 125, 500),
    ],
    &[Cmd::Move(150, 375), Cmd::Line(850, 375)],
    &[Cmd::Move(150, 625), Cmd::Line(850, 625)],
    &[
        Cmd::Move(479, 125),
        Cmd::Cubic(336, 354, 336, 646, 479, 875),
    ],
    &[
        Cmd::Move(521, 125),
        Cmd::Cubic(664, 354, 664, 646, 521, 875),
    ],
];

/// `refresh` from Tabler Icons.
static REFRESH: &[&[Cmd]] = &[
    &[
        Cmd::Move(833, 458),
        Cmd::Cubic(812, 308, 693, 190, 542, 170),
        Cmd::Cubic(391, 151, 246, 235, 188, 375),
        Cmd::Move(167, 208),
        Cmd::Line(167, 375),
        Cmd::Line(333, 375),
    ],
    &[
        Cmd::Move(167, 542),
        Cmd::Cubic(188, 692, 307, 810, 458, 830),
        Cmd::Cubic(609, 849, 754, 765, 813, 625),
        Cmd::Move(833, 792),
        Cmd::Line(833, 625),
        Cmd::Line(667, 625),
    ],
];

/// `dots` from Tabler Icons.
static MORE: &[&[Cmd]] = &[
    &[
        Cmd::Move(167, 500),
        Cmd::Cubic(167, 523, 185, 542, 208, 542),
        Cmd::Cubic(231, 542, 250, 523, 250, 500),
        Cmd::Cubic(250, 477, 231, 458, 208, 458),
        Cmd::Cubic(185, 458, 167, 477, 167, 500),
    ],
    &[
        Cmd::Move(458, 500),
        Cmd::Cubic(458, 523, 477, 542, 500, 542),
        Cmd::Cubic(523, 542, 542, 523, 542, 500),
        Cmd::Cubic(542, 477, 523, 458, 500, 458),
        Cmd::Cubic(477, 458, 458, 477, 458, 500),
    ],
    &[
        Cmd::Move(750, 500),
        Cmd::Cubic(750, 523, 769, 542, 792, 542),
        Cmd::Cubic(815, 542, 833, 523, 833, 500),
        Cmd::Cubic(833, 477, 815, 458, 792, 458),
        Cmd::Cubic(769, 458, 750, 477, 750, 500),
    ],
];

/// `bluetooth` from Tabler Icons.
static BLUETOOTH: &[&[Cmd]] = &[&[
    Cmd::Move(292, 333),
    Cmd::Line(708, 667),
    Cmd::Line(500, 833),
    Cmd::Line(500, 167),
    Cmd::Line(708, 333),
    Cmd::Line(292, 667),
]];

/// `key` from Tabler Icons.
static KEY: &[&[Cmd]] = &[
    &[
        Cmd::Move(690, 160),
        Cmd::Line(840, 310),
        Cmd::Cubic(862, 333, 875, 363, 875, 395),
        Cmd::Cubic(875, 427, 862, 457, 840, 480),
        Cmd::Line(730, 590),
        Cmd::Cubic(707, 612, 677, 625, 645, 625),
        Cmd::Cubic(613, 625, 583, 612, 560, 590),
        Cmd::Line(548, 577),
        Cmd::Line(274, 851),
        Cmd::Cubic(261, 864, 242, 873, 223, 875),
        Cmd::Line(216, 875),
        Cmd::Line(167, 875),
        Cmd::Cubic(146, 875, 128, 859, 125, 838),
        Cmd::Line(125, 833),
        Cmd::Line(125, 784),
        Cmd::Cubic(125, 765, 132, 746, 144, 731),
        Cmd::Line(149, 726),
        Cmd::Line(167, 708),
        Cmd::Line(250, 708),
        Cmd::Line(250, 625),
        Cmd::Line(333, 625),
        Cmd::Line(333, 542),
        Cmd::Line(423, 452),
        Cmd::Line(410, 440),
        Cmd::Cubic(388, 417, 375, 387, 375, 355),
        Cmd::Cubic(375, 323, 388, 293, 410, 270),
        Cmd::Line(520, 160),
        Cmd::Cubic(543, 138, 573, 125, 605, 125),
        Cmd::Cubic(637, 125, 667, 138, 690, 160),
    ],
    &[Cmd::Move(625, 375), Cmd::Line(625, 375)],
];

/// `magnet` from Tabler Icons.
static MAGNET: &[&[Cmd]] = &[
    &[
        Cmd::Move(167, 542),
        Cmd::Line(167, 208),
        Cmd::Cubic(167, 162, 204, 125, 250, 125),
        Cmd::Line(292, 125),
        Cmd::Cubic(338, 125, 375, 162, 375, 208),
        Cmd::Line(375, 542),
        Cmd::Cubic(375, 611, 431, 667, 500, 667),
        Cmd::Cubic(569, 667, 625, 611, 625, 542),
        Cmd::Line(625, 208),
        Cmd::Cubic(625, 162, 662, 125, 708, 125),
        Cmd::Line(750, 125),
        Cmd::Cubic(796, 125, 833, 162, 833, 208),
        Cmd::Line(833, 542),
        Cmd::Cubic(833, 726, 684, 875, 500, 875),
        Cmd::Cubic(316, 875, 167, 726, 167, 542),
    ],
    &[Cmd::Move(167, 333), Cmd::Line(375, 333)],
    &[Cmd::Move(625, 333), Cmd::Line(792, 333)],
];

/// `player-play` from Tabler Icons.
static PLAY: &[&[Cmd]] = &[&[
    Cmd::Move(292, 167),
    Cmd::Line(292, 833),
    Cmd::Line(833, 500),
    Cmd::Line(292, 167),
]];

/// `player-pause` from Tabler Icons.
static PAUSE: &[&[Cmd]] = &[
    &[
        Cmd::Move(250, 250),
        Cmd::Cubic(250, 227, 269, 208, 292, 208),
        Cmd::Line(375, 208),
        Cmd::Cubic(398, 208, 417, 227, 417, 250),
        Cmd::Line(417, 750),
        Cmd::Cubic(417, 773, 398, 792, 375, 792),
        Cmd::Line(292, 792),
        Cmd::Cubic(269, 792, 250, 773, 250, 750),
        Cmd::Line(250, 250),
    ],
    &[
        Cmd::Move(583, 250),
        Cmd::Cubic(583, 227, 602, 208, 625, 208),
        Cmd::Line(708, 208),
        Cmd::Cubic(731, 208, 750, 227, 750, 250),
        Cmd::Line(750, 750),
        Cmd::Cubic(750, 773, 731, 792, 708, 792),
        Cmd::Line(625, 792),
        Cmd::Cubic(602, 792, 583, 773, 583, 750),
        Cmd::Line(583, 250),
    ],
];

/// `rewind-backward-30` from Tabler Icons.
static REWIND30: &[&[Cmd]] = &[
    &[
        Cmd::Move(792, 686),
        Cmd::Cubic(869, 617, 896, 507, 858, 411),
        Cmd::Cubic(821, 314, 729, 250, 625, 250),
        Cmd::Line(167, 250),
    ],
    &[
        Cmd::Move(500, 646),
        Cmd::Line(500, 771),
        Cmd::Cubic(500, 805, 528, 833, 563, 833),
        Cmd::Cubic(597, 833, 625, 805, 625, 771),
        Cmd::Line(625, 646),
        Cmd::Cubic(625, 611, 597, 583, 563, 583),
        Cmd::Cubic(528, 583, 500, 611, 500, 646),
    ],
    &[
        Cmd::Move(250, 583),
        Cmd::Line(313, 583),
        Cmd::Cubic(347, 583, 375, 611, 375, 646),
        Cmd::Cubic(375, 680, 347, 708, 313, 708),
        Cmd::Line(292, 708),
        Cmd::Line(313, 708),
        Cmd::Cubic(347, 708, 375, 736, 375, 771),
        Cmd::Cubic(375, 805, 347, 833, 313, 833),
        Cmd::Line(250, 833),
    ],
    &[
        Cmd::Move(292, 375),
        Cmd::Line(167, 250),
        Cmd::Line(292, 125),
    ],
];

/// `rewind-forward-30` from Tabler Icons.
static FORWARD30: &[&[Cmd]] = &[
    &[
        Cmd::Move(209, 687),
        Cmd::Cubic(131, 618, 104, 508, 141, 411),
        Cmd::Cubic(178, 314, 271, 250, 375, 250),
        Cmd::Line(833, 250),
    ],
    &[
        Cmd::Move(625, 646),
        Cmd::Line(625, 771),
        Cmd::Cubic(625, 805, 653, 833, 688, 833),
        Cmd::Cubic(722, 833, 750, 805, 750, 771),
        Cmd::Line(750, 646),
        Cmd::Cubic(750, 611, 722, 583, 688, 583),
        Cmd::Cubic(653, 583, 625, 611, 625, 646),
    ],
    &[
        Cmd::Move(708, 375),
        Cmd::Line(833, 250),
        Cmd::Line(708, 125),
    ],
    &[
        Cmd::Move(375, 583),
        Cmd::Line(438, 583),
        Cmd::Cubic(472, 583, 500, 611, 500, 646),
        Cmd::Cubic(500, 680, 472, 708, 438, 708),
        Cmd::Line(417, 708),
        Cmd::Line(438, 708),
        Cmd::Cubic(472, 708, 500, 736, 500, 771),
        Cmd::Cubic(500, 805, 472, 833, 438, 833),
        Cmd::Line(375, 833),
    ],
];

/// `volume-2` from Tabler Icons.
static VOLUME_DOWN: &[&[Cmd]] = &[
    &[
        Cmd::Move(625, 333),
        Cmd::Cubic(677, 373, 708, 434, 708, 500),
        Cmd::Cubic(708, 566, 677, 627, 625, 667),
    ],
    &[
        Cmd::Move(250, 625),
        Cmd::Line(167, 625),
        Cmd::Cubic(144, 625, 125, 606, 125, 583),
        Cmd::Line(125, 417),
        Cmd::Cubic(125, 394, 144, 375, 167, 375),
        Cmd::Line(250, 375),
        Cmd::Line(396, 188),
        Cmd::Cubic(403, 173, 420, 166, 436, 171),
        Cmd::Cubic(452, 176, 461, 192, 458, 208),
        Cmd::Line(458, 792),
        Cmd::Cubic(461, 808, 452, 824, 436, 829),
        Cmd::Cubic(420, 834, 403, 827, 396, 813),
        Cmd::Line(250, 625),
    ],
];

/// `volume` from Tabler Icons.
static VOLUME_UP: &[&[Cmd]] = &[
    &[
        Cmd::Move(625, 333),
        Cmd::Cubic(677, 373, 708, 434, 708, 500),
        Cmd::Cubic(708, 566, 677, 627, 625, 667),
    ],
    &[
        Cmd::Move(737, 208),
        Cmd::Cubic(826, 280, 877, 387, 877, 500),
        Cmd::Cubic(877, 613, 826, 720, 737, 792),
    ],
    &[
        Cmd::Move(250, 625),
        Cmd::Line(167, 625),
        Cmd::Cubic(144, 625, 125, 606, 125, 583),
        Cmd::Line(125, 417),
        Cmd::Cubic(125, 394, 144, 375, 167, 375),
        Cmd::Line(250, 375),
        Cmd::Line(396, 188),
        Cmd::Cubic(403, 173, 420, 166, 436, 171),
        Cmd::Cubic(452, 176, 461, 192, 458, 208),
        Cmd::Line(458, 792),
        Cmd::Cubic(461, 808, 452, 824, 436, 829),
        Cmd::Cubic(420, 834, 403, 827, 396, 813),
        Cmd::Line(250, 625),
    ],
];

/// `dots-vertical` from Tabler Icons.
static MORE_VERTICAL: &[&[Cmd]] = &[
    &[
        Cmd::Move(458, 500),
        Cmd::Cubic(458, 523, 477, 542, 500, 542),
        Cmd::Cubic(523, 542, 542, 523, 542, 500),
        Cmd::Cubic(542, 477, 523, 458, 500, 458),
        Cmd::Cubic(477, 458, 458, 477, 458, 500),
    ],
    &[
        Cmd::Move(458, 792),
        Cmd::Cubic(458, 815, 477, 833, 500, 833),
        Cmd::Cubic(523, 833, 542, 815, 542, 792),
        Cmd::Cubic(542, 769, 523, 750, 500, 750),
        Cmd::Cubic(477, 750, 458, 769, 458, 792),
    ],
    &[
        Cmd::Move(458, 208),
        Cmd::Cubic(458, 231, 477, 250, 500, 250),
        Cmd::Cubic(523, 250, 542, 231, 542, 208),
        Cmd::Cubic(542, 185, 523, 167, 500, 167),
        Cmd::Cubic(477, 167, 458, 185, 458, 208),
    ],
];

/// `chevron-left` from Tabler Icons.
static PREVIOUS: &[&[Cmd]] = &[&[
    Cmd::Move(625, 250),
    Cmd::Line(375, 500),
    Cmd::Line(625, 750),
]];

/// `chevron-right` from Tabler Icons.
static NEXT: &[&[Cmd]] = &[&[
    Cmd::Move(375, 250),
    Cmd::Line(625, 500),
    Cmd::Line(375, 750),
]];

/// `trash` from Tabler Icons.
static TRASH: &[&[Cmd]] = &[
    &[Cmd::Move(167, 292), Cmd::Line(833, 292)],
    &[Cmd::Move(417, 458), Cmd::Line(417, 708)],
    &[Cmd::Move(583, 458), Cmd::Line(583, 708)],
    &[
        Cmd::Move(208, 292),
        Cmd::Line(250, 792),
        Cmd::Cubic(250, 838, 287, 875, 333, 875),
        Cmd::Line(667, 875),
        Cmd::Cubic(713, 875, 750, 838, 750, 792),
        Cmd::Line(792, 292),
    ],
    &[
        Cmd::Move(375, 292),
        Cmd::Line(375, 167),
        Cmd::Cubic(375, 144, 394, 125, 417, 125),
        Cmd::Line(583, 125),
        Cmd::Cubic(606, 125, 625, 144, 625, 167),
        Cmd::Line(625, 292),
    ],
];

/// `wifi` from Tabler Icons.
static WIFI: &[&[Cmd]] = &[
    &[Cmd::Move(500, 750), Cmd::Line(500, 750)],
    &[
        Cmd::Move(382, 632),
        Cmd::Cubic(447, 567, 553, 567, 618, 632),
    ],
    &[
        Cmd::Move(264, 514),
        Cmd::Cubic(327, 452, 412, 417, 500, 417),
        Cmd::Cubic(588, 417, 673, 452, 736, 514),
    ],
    &[
        Cmd::Move(146, 396),
        Cmd::Cubic(342, 201, 658, 201, 855, 396),
    ],
];

/// `battery` from Tabler Icons.
static BATTERY: &[&[Cmd]] = &[&[
    Cmd::Move(250, 292),
    Cmd::Line(708, 292),
    Cmd::Cubic(754, 292, 792, 329, 792, 375),
    Cmd::Line(792, 396),
    Cmd::Cubic(792, 407, 801, 417, 813, 417),
    Cmd::Cubic(824, 417, 833, 426, 833, 438),
    Cmd::Line(833, 563),
    Cmd::Cubic(833, 574, 824, 583, 813, 583),
    Cmd::Cubic(801, 583, 792, 593, 792, 604),
    Cmd::Line(792, 625),
    Cmd::Cubic(792, 671, 754, 708, 708, 708),
    Cmd::Line(250, 708),
    Cmd::Cubic(204, 708, 167, 671, 167, 625),
    Cmd::Line(167, 375),
    Cmd::Cubic(167, 329, 204, 292, 250, 292),
]];

/// `plus` from Tabler Icons.
static PLUS: &[&[Cmd]] = &[
    &[Cmd::Move(500, 208), Cmd::Line(500, 792)],
    &[Cmd::Move(208, 500), Cmd::Line(792, 500)],
];

/// `headphones` from Tabler Icons.
static HEADPHONES: &[&[Cmd]] = &[
    &[
        Cmd::Move(167, 625),
        Cmd::Cubic(167, 579, 204, 542, 250, 542),
        Cmd::Line(292, 542),
        Cmd::Cubic(338, 542, 375, 579, 375, 625),
        Cmd::Line(375, 750),
        Cmd::Cubic(375, 796, 338, 833, 292, 833),
        Cmd::Line(250, 833),
        Cmd::Cubic(204, 833, 167, 796, 167, 750),
        Cmd::Line(167, 625),
    ],
    &[
        Cmd::Move(625, 625),
        Cmd::Cubic(625, 579, 662, 542, 708, 542),
        Cmd::Line(750, 542),
        Cmd::Cubic(796, 542, 833, 579, 833, 625),
        Cmd::Line(833, 750),
        Cmd::Cubic(833, 796, 796, 833, 750, 833),
        Cmd::Line(708, 833),
        Cmd::Cubic(662, 833, 625, 796, 625, 750),
        Cmd::Line(625, 625),
    ],
    &[
        Cmd::Move(167, 625),
        Cmd::Line(167, 500),
        Cmd::Cubic(167, 316, 316, 167, 500, 167),
        Cmd::Cubic(684, 167, 833, 316, 833, 500),
        Cmd::Line(833, 625),
    ],
];

/// `minus` from Tabler Icons.
static MINUS: &[&[Cmd]] = &[&[Cmd::Move(208, 500), Cmd::Line(792, 500)]];

/// `arrows-up-down` from Tabler Icons.
static SWAP_VERTICAL: &[&[Cmd]] = &[
    &[Cmd::Move(292, 125), Cmd::Line(292, 875)],
    &[
        Cmd::Move(417, 250),
        Cmd::Line(292, 125),
        Cmd::Line(167, 250),
    ],
    &[
        Cmd::Move(833, 750),
        Cmd::Line(708, 875),
        Cmd::Line(583, 750),
    ],
    &[Cmd::Move(708, 875), Cmd::Line(708, 125)],
];

/// `chess-king` from Tabler Icons.
static CHESS_WHITE_KING: &[&[Cmd]] = &[
    &[
        Cmd::Move(333, 667),
        Cmd::Line(273, 697),
        Cmd::Cubic(259, 704, 250, 718, 250, 734),
        Cmd::Line(250, 833),
        Cmd::Line(750, 833),
        Cmd::Line(750, 734),
        Cmd::Cubic(750, 718, 741, 704, 727, 697),
        Cmd::Line(667, 667),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(354, 667),
        Cmd::Cubic(282, 667, 221, 614, 210, 542),
        Cmd::Cubic(199, 471, 243, 402, 312, 381),
        Cmd::Cubic(381, 360, 455, 393, 486, 458),
        Cmd::Line(514, 458),
        Cmd::Cubic(545, 393, 619, 360, 688, 381),
        Cmd::Cubic(757, 402, 801, 471, 790, 542),
        Cmd::Cubic(779, 614, 718, 667, 646, 667),
        Cmd::Line(354, 667),
    ],
    &[Cmd::Move(375, 250), Cmd::Line(625, 250)],
    &[Cmd::Move(500, 125), Cmd::Line(500, 458)],
];

/// `chess-queen` from Tabler Icons.
static CHESS_WHITE_QUEEN: &[&[Cmd]] = &[
    &[
        Cmd::Move(667, 667),
        Cmd::Line(750, 208),
        Cmd::Line(583, 375),
        Cmd::Line(500, 167),
        Cmd::Line(417, 375),
        Cmd::Line(250, 208),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(333, 667),
        Cmd::Line(273, 697),
        Cmd::Cubic(259, 704, 250, 718, 250, 734),
        Cmd::Line(250, 833),
        Cmd::Line(750, 833),
        Cmd::Line(750, 734),
        Cmd::Cubic(750, 718, 741, 704, 727, 697),
        Cmd::Line(667, 667),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(458, 167),
        Cmd::Cubic(458, 190, 477, 208, 500, 208),
        Cmd::Cubic(523, 208, 542, 190, 542, 167),
        Cmd::Cubic(542, 144, 523, 125, 500, 125),
        Cmd::Cubic(477, 125, 458, 144, 458, 167),
    ],
    &[
        Cmd::Move(208, 208),
        Cmd::Cubic(208, 231, 227, 250, 250, 250),
        Cmd::Cubic(273, 250, 292, 231, 292, 208),
        Cmd::Cubic(292, 185, 273, 167, 250, 167),
        Cmd::Cubic(227, 167, 208, 185, 208, 208),
    ],
    &[
        Cmd::Move(708, 208),
        Cmd::Cubic(708, 231, 727, 250, 750, 250),
        Cmd::Cubic(773, 250, 792, 231, 792, 208),
        Cmd::Cubic(792, 185, 773, 167, 750, 167),
        Cmd::Cubic(727, 167, 708, 185, 708, 208),
    ],
];

/// `chess-rook` from Tabler Icons.
static CHESS_WHITE_ROOK: &[&[Cmd]] = &[
    &[
        Cmd::Move(333, 667),
        Cmd::Line(273, 697),
        Cmd::Cubic(259, 704, 250, 718, 250, 734),
        Cmd::Line(250, 833),
        Cmd::Line(750, 833),
        Cmd::Line(750, 734),
        Cmd::Cubic(750, 718, 741, 704, 727, 697),
        Cmd::Line(667, 667),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(333, 667),
        Cmd::Line(375, 292),
        Cmd::Line(625, 292),
        Cmd::Line(667, 667),
    ],
    &[
        Cmd::Move(250, 167),
        Cmd::Line(271, 292),
        Cmd::Line(729, 292),
        Cmd::Line(750, 167),
    ],
    &[Cmd::Move(417, 167), Cmd::Line(417, 292)],
    &[Cmd::Move(583, 167), Cmd::Line(583, 292)],
];

/// `chess-bishop` from Tabler Icons.
static CHESS_WHITE_BISHOP: &[&[Cmd]] = &[
    &[
        Cmd::Move(333, 667),
        Cmd::Line(273, 697),
        Cmd::Cubic(259, 704, 250, 718, 250, 734),
        Cmd::Line(250, 833),
        Cmd::Line(750, 833),
        Cmd::Line(750, 734),
        Cmd::Cubic(750, 718, 741, 704, 727, 697),
        Cmd::Line(667, 667),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(458, 167),
        Cmd::Cubic(458, 190, 477, 208, 500, 208),
        Cmd::Cubic(523, 208, 542, 190, 542, 167),
        Cmd::Cubic(542, 144, 523, 125, 500, 125),
        Cmd::Cubic(477, 125, 458, 144, 458, 167),
    ],
    &[
        Cmd::Move(396, 667),
        Cmd::Cubic(326, 667, 292, 597, 292, 542),
        Cmd::Cubic(292, 389, 361, 292, 500, 250),
        Cmd::Cubic(639, 292, 708, 393, 708, 542),
        Cmd::Cubic(708, 595, 676, 662, 611, 667),
        Cmd::Line(604, 667),
        Cmd::Line(396, 667),
    ],
    &[Cmd::Move(625, 333), Cmd::Line(500, 458)],
    &[Cmd::Move(500, 208), Cmd::Line(500, 250)],
];

/// `chess-knight` from Tabler Icons.
static CHESS_WHITE_KNIGHT: &[&[Cmd]] = &[
    &[
        Cmd::Move(333, 667),
        Cmd::Line(273, 697),
        Cmd::Cubic(259, 704, 250, 718, 250, 734),
        Cmd::Line(250, 833),
        Cmd::Line(750, 833),
        Cmd::Line(750, 734),
        Cmd::Cubic(750, 718, 741, 704, 727, 697),
        Cmd::Line(667, 667),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(375, 125),
        Cmd::Line(417, 250),
        Cmd::Line(271, 339),
        Cmd::Cubic(255, 349, 248, 368, 253, 386),
        Cmd::Cubic(258, 404, 274, 417, 293, 417),
        Cmd::Line(417, 417),
        Cmd::Line(330, 667),
        Cmd::Line(662, 667),
        Cmd::Line(667, 458),
        Cmd::Cubic(667, 333, 621, 209, 500, 167),
        Cmd::Cubic(419, 138, 378, 125, 375, 125),
    ],
];

/// `chess` from Tabler Icons.
static CHESS_WHITE_PAWN: &[&[Cmd]] = &[
    &[
        Cmd::Move(500, 125),
        Cmd::Cubic(569, 125, 625, 181, 625, 250),
        Cmd::Cubic(625, 296, 600, 353, 563, 375),
        Cmd::Line(625, 667),
        Cmd::Line(375, 667),
        Cmd::Line(438, 375),
        Cmd::Cubic(400, 353, 375, 296, 375, 250),
        Cmd::Cubic(375, 181, 431, 125, 500, 125),
    ],
    &[Cmd::Move(333, 375), Cmd::Line(667, 375)],
    &[
        Cmd::Move(279, 699),
        Cmd::Cubic(261, 705, 250, 720, 250, 738),
        Cmd::Line(250, 792),
        Cmd::Cubic(250, 815, 269, 833, 292, 833),
        Cmd::Line(708, 833),
        Cmd::Cubic(731, 833, 750, 815, 750, 792),
        Cmd::Line(750, 738),
        Cmd::Cubic(750, 720, 739, 704, 722, 699),
        Cmd::Line(625, 667),
        Cmd::Line(375, 667),
        Cmd::Line(279, 699),
    ],
];

/// `chess-king` from Tabler Icons.
static CHESS_BLACK_KING: &[&[Cmd]] = &[
    &[
        Cmd::Move(333, 667),
        Cmd::Line(273, 697),
        Cmd::Cubic(259, 704, 250, 718, 250, 734),
        Cmd::Line(250, 833),
        Cmd::Line(750, 833),
        Cmd::Line(750, 734),
        Cmd::Cubic(750, 718, 741, 704, 727, 697),
        Cmd::Line(667, 667),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(354, 667),
        Cmd::Cubic(282, 667, 221, 614, 210, 542),
        Cmd::Cubic(199, 471, 243, 402, 312, 381),
        Cmd::Cubic(381, 360, 455, 393, 486, 458),
        Cmd::Line(514, 458),
        Cmd::Cubic(545, 393, 619, 360, 688, 381),
        Cmd::Cubic(757, 402, 801, 471, 790, 542),
        Cmd::Cubic(779, 614, 718, 667, 646, 667),
        Cmd::Line(354, 667),
    ],
    &[Cmd::Move(375, 250), Cmd::Line(625, 250)],
    &[Cmd::Move(500, 125), Cmd::Line(500, 458)],
];

/// `chess-queen` from Tabler Icons.
static CHESS_BLACK_QUEEN: &[&[Cmd]] = &[
    &[
        Cmd::Move(667, 667),
        Cmd::Line(750, 208),
        Cmd::Line(583, 375),
        Cmd::Line(500, 167),
        Cmd::Line(417, 375),
        Cmd::Line(250, 208),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(333, 667),
        Cmd::Line(273, 697),
        Cmd::Cubic(259, 704, 250, 718, 250, 734),
        Cmd::Line(250, 833),
        Cmd::Line(750, 833),
        Cmd::Line(750, 734),
        Cmd::Cubic(750, 718, 741, 704, 727, 697),
        Cmd::Line(667, 667),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(458, 167),
        Cmd::Cubic(458, 190, 477, 208, 500, 208),
        Cmd::Cubic(523, 208, 542, 190, 542, 167),
        Cmd::Cubic(542, 144, 523, 125, 500, 125),
        Cmd::Cubic(477, 125, 458, 144, 458, 167),
    ],
    &[
        Cmd::Move(208, 208),
        Cmd::Cubic(208, 231, 227, 250, 250, 250),
        Cmd::Cubic(273, 250, 292, 231, 292, 208),
        Cmd::Cubic(292, 185, 273, 167, 250, 167),
        Cmd::Cubic(227, 167, 208, 185, 208, 208),
    ],
    &[
        Cmd::Move(708, 208),
        Cmd::Cubic(708, 231, 727, 250, 750, 250),
        Cmd::Cubic(773, 250, 792, 231, 792, 208),
        Cmd::Cubic(792, 185, 773, 167, 750, 167),
        Cmd::Cubic(727, 167, 708, 185, 708, 208),
    ],
];

/// `chess-rook` from Tabler Icons.
static CHESS_BLACK_ROOK: &[&[Cmd]] = &[
    &[
        Cmd::Move(333, 667),
        Cmd::Line(273, 697),
        Cmd::Cubic(259, 704, 250, 718, 250, 734),
        Cmd::Line(250, 833),
        Cmd::Line(750, 833),
        Cmd::Line(750, 734),
        Cmd::Cubic(750, 718, 741, 704, 727, 697),
        Cmd::Line(667, 667),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(333, 667),
        Cmd::Line(375, 292),
        Cmd::Line(625, 292),
        Cmd::Line(667, 667),
    ],
    &[
        Cmd::Move(250, 167),
        Cmd::Line(271, 292),
        Cmd::Line(729, 292),
        Cmd::Line(750, 167),
    ],
    &[Cmd::Move(417, 167), Cmd::Line(417, 292)],
    &[Cmd::Move(583, 167), Cmd::Line(583, 292)],
];

/// `chess-bishop` from Tabler Icons.
static CHESS_BLACK_BISHOP: &[&[Cmd]] = &[
    &[
        Cmd::Move(333, 667),
        Cmd::Line(273, 697),
        Cmd::Cubic(259, 704, 250, 718, 250, 734),
        Cmd::Line(250, 833),
        Cmd::Line(750, 833),
        Cmd::Line(750, 734),
        Cmd::Cubic(750, 718, 741, 704, 727, 697),
        Cmd::Line(667, 667),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(458, 167),
        Cmd::Cubic(458, 190, 477, 208, 500, 208),
        Cmd::Cubic(523, 208, 542, 190, 542, 167),
        Cmd::Cubic(542, 144, 523, 125, 500, 125),
        Cmd::Cubic(477, 125, 458, 144, 458, 167),
    ],
    &[
        Cmd::Move(396, 667),
        Cmd::Cubic(326, 667, 292, 597, 292, 542),
        Cmd::Cubic(292, 389, 361, 292, 500, 250),
        Cmd::Cubic(639, 292, 708, 393, 708, 542),
        Cmd::Cubic(708, 595, 676, 662, 611, 667),
        Cmd::Line(604, 667),
        Cmd::Line(396, 667),
    ],
    &[Cmd::Move(625, 333), Cmd::Line(500, 458)],
    &[Cmd::Move(500, 208), Cmd::Line(500, 250)],
];

/// `chess-knight` from Tabler Icons.
static CHESS_BLACK_KNIGHT: &[&[Cmd]] = &[
    &[
        Cmd::Move(333, 667),
        Cmd::Line(273, 697),
        Cmd::Cubic(259, 704, 250, 718, 250, 734),
        Cmd::Line(250, 833),
        Cmd::Line(750, 833),
        Cmd::Line(750, 734),
        Cmd::Cubic(750, 718, 741, 704, 727, 697),
        Cmd::Line(667, 667),
        Cmd::Line(333, 667),
    ],
    &[
        Cmd::Move(375, 125),
        Cmd::Line(417, 250),
        Cmd::Line(271, 339),
        Cmd::Cubic(255, 349, 248, 368, 253, 386),
        Cmd::Cubic(258, 404, 274, 417, 293, 417),
        Cmd::Line(417, 417),
        Cmd::Line(330, 667),
        Cmd::Line(662, 667),
        Cmd::Line(667, 458),
        Cmd::Cubic(667, 333, 621, 209, 500, 167),
        Cmd::Cubic(419, 138, 378, 125, 375, 125),
    ],
];

/// `chess` from Tabler Icons.
static CHESS_BLACK_PAWN: &[&[Cmd]] = &[
    &[
        Cmd::Move(500, 125),
        Cmd::Cubic(569, 125, 625, 181, 625, 250),
        Cmd::Cubic(625, 296, 600, 353, 563, 375),
        Cmd::Line(625, 667),
        Cmd::Line(375, 667),
        Cmd::Line(438, 375),
        Cmd::Cubic(400, 353, 375, 296, 375, 250),
        Cmd::Cubic(375, 181, 431, 125, 500, 125),
    ],
    &[Cmd::Move(333, 375), Cmd::Line(667, 375)],
    &[
        Cmd::Move(279, 699),
        Cmd::Cubic(261, 705, 250, 720, 250, 738),
        Cmd::Line(250, 792),
        Cmd::Cubic(250, 815, 269, 833, 292, 833),
        Cmd::Line(708, 833),
        Cmd::Cubic(731, 833, 750, 815, 750, 792),
        Cmd::Line(750, 738),
        Cmd::Cubic(750, 720, 739, 704, 722, 699),
        Cmd::Line(625, 667),
        Cmd::Line(375, 667),
        Cmd::Line(279, 699),
    ],
];
